# Generated by Django 5.1.7 on 2025-03-12 22:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform', models.CharField(choices=[('FACEBOOK', 'Facebook'), ('TELEGRAM', 'Telegram'), ('DISCORD', 'Discord')], max_length=20)),
                ('content', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='social_photos/')),
                ('video', models.FileField(blank=True, null=True, upload_to='social_videos/')),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hazard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hazard_type', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.location')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
